//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MonopolyCR {
	using System;
	
	
	/// <summary>
	///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
	/// </summary>
	// StronglyTypedResourceBuilder generó automáticamente esta clase
	// a través de una herramienta como ResGen o Visual Studio.
	// Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
	// con la opción /str o recompile su proyecto de VS.
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
	internal class Recursos {
		
		private static global::System.Resources.ResourceManager resourceMan;
		
		private static global::System.Globalization.CultureInfo resourceCulture;
		
		[global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
		internal Recursos() {
		}
		
		/// <summary>
		///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Resources.ResourceManager ResourceManager {
			get {
				if (object.ReferenceEquals(resourceMan, null)) {
					global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MonopolyCR.Recursos", typeof(Recursos).Assembly);
					resourceMan = temp;
				}
				return resourceMan;
			}
		}
		
		/// <summary>
		///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
		///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
		/// </summary>
		[global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
		internal static global::System.Globalization.CultureInfo Culture {
			get {
				return resourceCulture;
			}
			set {
				resourceCulture = value;
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap alajuela {
			get {
				object obj = ResourceManager.GetObject("alajuela", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap alajuelaGrecia {
			get {
				object obj = ResourceManager.GetObject("alajuelaGrecia", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap alajuelaGuacima {
			get {
				object obj = ResourceManager.GetObject("alajuelaGuacima", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap alajuelaJuan_santa_maria {
			get {
				object obj = ResourceManager.GetObject("alajuelaJuan santa maria", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap alajuelaPoas {
			get {
				object obj = ResourceManager.GetObject("alajuelaPoas", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap cafe {
			get {
				object obj = ResourceManager.GetObject("cafe", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap cartago {
			get {
				object obj = ResourceManager.GetObject("cartago", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap CartagoGuarco {
			get {
				object obj = ResourceManager.GetObject("CartagoGuarco", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap cartagoOrosi {
			get {
				object obj = ResourceManager.GetObject("cartagoOrosi", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap cartagoRuina {
			get {
				object obj = ResourceManager.GetObject("cartagoRuina", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap cartagoTren {
			get {
				object obj = ResourceManager.GetObject("cartagoTren", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap compAyA {
			get {
				object obj = ResourceManager.GetObject("compAyA", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap compIce {
			get {
				object obj = ResourceManager.GetObject("compIce", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap compINTEL {
			get {
				object obj = ResourceManager.GetObject("compINTEL", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap compsky {
			get {
				object obj = ResourceManager.GetObject("compsky", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap costa_rica {
			get {
				object obj = ResourceManager.GetObject("costa_rica", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap dado1 {
			get {
				object obj = ResourceManager.GetObject("dado1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap dado2 {
			get {
				object obj = ResourceManager.GetObject("dado2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap dado3 {
			get {
				object obj = ResourceManager.GetObject("dado3", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap dado4 {
			get {
				object obj = ResourceManager.GetObject("dado4", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap dado5 {
			get {
				object obj = ResourceManager.GetObject("dado5", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap dado6 {
			get {
				object obj = ResourceManager.GetObject("dado6", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap guanacasteLiberia {
			get {
				object obj = ResourceManager.GetObject("guanacasteLiberia", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap guanacasteNicoya {
			get {
				object obj = ResourceManager.GetObject("guanacasteNicoya", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap guanacasteOduber {
			get {
				object obj = ResourceManager.GetObject("guanacasteOduber", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap guanacasteTempisque {
			get {
				object obj = ResourceManager.GetObject("guanacasteTempisque", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap heredia {
			get {
				object obj = ResourceManager.GetObject("heredia", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap herediaBelen {
			get {
				object obj = ResourceManager.GetObject("herediaBelen", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap herediaSanRafael {
			get {
				object obj = ResourceManager.GetObject("herediaSanRafael", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap ima {
			get {
				object obj = ResourceManager.GetObject("ima", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Ima2 {
			get {
				object obj = ResourceManager.GetObject("Ima2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Imagen1 {
			get {
				object obj = ResourceManager.GetObject("Imagen1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap images {
			get {
				object obj = ResourceManager.GetObject("images", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap imagesDev {
			get {
				object obj = ResourceManager.GetObject("imagesDev", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Jugador1 {
			get {
				object obj = ResourceManager.GetObject("Jugador1", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap Jugador2 {
			get {
				object obj = ResourceManager.GetObject("Jugador2", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap limonAeropuerto_ {
			get {
				object obj = ResourceManager.GetObject("limonAeropuerto ", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap limonRuta {
			get {
				object obj = ResourceManager.GetObject("limonRuta", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap limonTortuguero {
			get {
				object obj = ResourceManager.GetObject("limonTortuguero", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap LosSuenosJaco {
			get {
				object obj = ResourceManager.GetObject("LosSuenosJaco", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap MAN_06 {
			get {
				object obj = ResourceManager.GetObject("MAN_06", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap mapa {
			get {
				object obj = ResourceManager.GetObject("mapa", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap monopoly_run {
			get {
				object obj = ResourceManager.GetObject("monopoly-run", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap poas_volcano {
			get {
				object obj = ResourceManager.GetObject("poas_volcano", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap puerto_Limon {
			get {
				object obj = ResourceManager.GetObject("puerto Limon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap puertoLimon {
			get {
				object obj = ResourceManager.GetObject("puertoLimon", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap puntarenas {
			get {
				object obj = ResourceManager.GetObject("puntarenas", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap puntarenasJaco {
			get {
				object obj = ResourceManager.GetObject("puntarenasJaco", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap puntManuel {
			get {
				object obj = ResourceManager.GetObject("puntManuel", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap sanJose {
			get {
				object obj = ResourceManager.GetObject("sanJose", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap sanJoseSantaAna {
			get {
				object obj = ResourceManager.GetObject("sanJoseSantaAna", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap SanJoseTobias {
			get {
				object obj = ResourceManager.GetObject("SanJoseTobias", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap SanJoseTurrialba {
			get {
				object obj = ResourceManager.GetObject("SanJoseTurrialba", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
		
		/// <summary>
		///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
		/// </summary>
		internal static System.Drawing.Bitmap volcanArenal {
			get {
				object obj = ResourceManager.GetObject("volcanArenal", resourceCulture);
				return ((System.Drawing.Bitmap)(obj));
			}
		}
	}
}
